### PR TITLE
dont publish .git directories

### PR DESCRIPTION
**Pull request by azweb76**
.git directories are causing Jenkins build issues for our apps

### CODE REVIEW

**Review by lmle — APPROVED** [review]

**Comment by augusto-altman** [comment]
+1 we are facing the same issue

**Comment by azweb76** [comment]
can someone bump the version and publish?

**Review by paulodiovani — APPROVED** [review]

**Review by iagodahlem — APPROVED** [review]

**Comment by azweb76** [comment]
@sebmarkbage any chance you can merge this and publish a new version?

**Comment by leuasseurfarrelds247-arch** [comment]
20b1462e35c330b60c746112feb6640edc1f18b3

**Pull request merged**
